[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "sbum"
description = "A TUI for the Slurm Workload Manager."
requires-python = ">=3.8"
license = "MIT"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[project.urls]
Repository = "https://github.com/laitifranz/turm"

[tool.maturin]
bindings = "bin"
strip = true
